# Generated by Django 4.2.29 on 2026-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['week_number', 'day', 'start_time']},
        ),
    ]
